#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor -d I II III IV V VI VII VIII IX X

# Background
nitrogen --set-zoom-fill ~/downloads/trueclarity2.png &

# Layout
bspc config border_width         2
bspc config window_gap          4
bspc config top_padding          32
bspc config bottom_padding        4
bspc config left_padding          4
bspc config right_padding         4

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

# Gruvbox border colors
bspc config focused_border_color  "#c8a050"
bspc config normal_border_color   "#221c15"
bspc config active_border_color   "#2e2418"
bspc config presel_feedback_color "#7ab0c8"

# Rules
bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off

# Autostart
picom --daemon &
~/.config/polybar/launch.sh &
